name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  node-ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.3.0

      - name: Setup Nodejs and npm
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Setup yarn
        run: npm install -g yarn

      - name: Run tests
        run: yarn test

      - name: Run linter
        run: yarn lint

      - name: Build the application
        run: yarn build

      - name: Build Storybook
        run: sudo yarn storybook:build
